name: Build & Deploy to branch

env:
  DEPLOY_BRANCH: unzip # Configure the destination branch

on:
  push:
    branches: [ main ] # Configure the branchs which you want to run this workflow
    
jobs:
  build-push:
    name: "Build & Push"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*] # Configure nodejs version

    steps:

    # Checkout source code
    - name: Checkout
      uses: actions/checkout@v2
      
    # Setup Nodejs
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Build application into BUILD directory
    - name: Build application
      run: |
        node unzip.js
        unzip files.zip -d out
        touch ./out/.nojekyll

    # Synchronize & push BUILD directory to deployment branch
    - name: Configure Git informations
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
        

    - name: New branch & push into deployment branch
      run: |
        GIT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
        DEPLOY_BRANCH=$DEPLOY_BRANCH
        GIT_COMMIT=$(git rev-parse --short HEAD)

        echo "Checking out $DEPLOY_BRANCH"
        git checkout -b $DEPLOY_BRANCH
        git push origin $DEPLOY_BRANCH
        cd ..
